### ISSUE TITLE
Client discovery: Error receiving datagram

### ISSUE THREAD

**Issue by imsodin** [Nutomic/syncthing-java#8]
I run `./gradlew run -Pargs="-d BPDFDTU-..."` on 1f1bb33fa650a244985b5893c223c2aeffdb37fc, which results in the following error:

```
15:09:40.955 [pool-7-thread-1] WARN net.syncthing.java.discovery.protocol.LocalDiscoveryHandler - Error receiving datagram
java.net.SocketException: Socket closed
	at java.net.PlainDatagramSocketImpl.receive0(Native Method)
	at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:143)
	at java.net.DatagramSocket.receive(DatagramSocket.java:812)
	at net.syncthing.java.discovery.protocol.LocalDiscoveryHandler$2.run(LocalDiscoveryHandler.java:151)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Entire log: https://gist.github.com/imsodin/6b640daf58cc490ce40e185a259a9219

Might be related to #5 

I haven't looked into it at all yet, as I tried to find out how debugging in Android Studio or linux command line works for a java gradle project - I got a little annoyed in the process. If you have the inclination to tell me a bit about your workflow and/or answer a few questions, ping me in IRC.

**Comment by Nutomic** [comment]
That exception is just thrown because the listening socket is closed while another thread is still listening. I've added some code so this specific exception is ignored.

The easiest option for debugging is with IntelliJ IDEA, and set this run configuration. Then you can run or debug directly from the IDE. Alternatively, use the instructions in the syncthing-lite readme to compile the dev version on Android.

![screenshot_20180107_130655](https://user-images.githubusercontent.com/1044450/34646447-d32e2df2-f3ab-11e7-839d-bd16d4f31f21.png)
